# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdac6abf75a602ce183de9dc5f687eb769c28a236919510175dcf71165db5466f3535b76d12f688ce2eb486f5b2d5d94d078f49a978b2594e969dd6b7e27b250

test:
  secret_key_base: 04ca695295cfe30d522dc5a3940dd647b3438f602959c10ae4ed69be4b584df4a25fb73f409713a913c2e6c5c442f4c4fa79beba4c3ab46428a1dc7788287001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
